- name: Group of hosts
  hosts: "{{ group | default('all_workers') }}"
  tasks:
 
  - name: Show OS and Version (from gather_facts)
    ansible.builtin.debug:
      msg:
        - "{{ ansible_os_family }} -- {{ ansible_distribution }} -- v. {{ ansible_distribution_version }}"
 
  - name: Show All mounts (from gether_facts)
    ansible.builtin.debug:
      msg:
        - "-MOUNTS-INFO--------"
        - "Dev {{ item.device }} mounted as {{ item.mount }} and has size available {{(item.size_available / 1024 / 1024) | round}} Mb"
        - "Capasity {{(item.size_total / 1024 / 1024 ) | round}} Mb"
        - "Used {{((item.size_total - item.size_available) / 1024 / 1024) | round}} Mb"
        - "--------------------"
    with_items: "{{ ansible_facts.mounts }}"
    loop_control:
      label: "{{ item.mount }}"

  - name: Show memory (from gether_facts)
    vars:
      m_total: "{{ ansible_memory_mb.real.total }}"
      m_used: "{{ ansible_memory_mb.real.used }}"
      ms_total: "{{ ansible_memory_mb.swap.total }}"
      ms_used: "{{ ansible_memory_mb.swap.used }}"
    ansible.builtin.debug:
      msg:
        - "-MEMORY-INFO--------"
        - "Total RAM is {{ m_total }} Mb"
        - "Used RAM is {{m_used}} Mb"
        - "Total RAM (with swap) is {{ m_total | int + ms_total | int }} Mb"
        - "Used RAM ( with swap) is {{ m_used | int + ms_used | int }} Mb"
        - "--------------------"
